/** 20 paragraphs of lorem ipsum. */
const loremIpsum: string = `Lorem ipsum dolor sit amet. Quo perspiciatis molestiae ut consequatur fuga et debitis voluptatem non beatae adipisci. In dolore tenetur est voluptas internos non quibusdam odit! Et fugiat provident et dolorem illum ut ipsam illo. Nam Quis cupiditate et maxime tempora in optio sunt!
Rem consectetur ipsa id voluptas sint qui voluptates dolorem qui repellendus deleniti et dolores nostrum et nostrum natus. In Quis quas id facere consequatur delectus unde qui recusandae esse?
Et doloremque doloremque et temporibus quod eos dolore officiis sit consequatur magnam. Est enim similique non impedit officia qui tenetur internos?
Hic nisi ipsam ut distinctio possimus quaerat sunt ut tempore Quis qui minus voluptatem eos ipsam enim. Est nihil nihil eum esse sint est laborum harum et rerum sapiente et voluptates tenetur non consequatur quia aut fugiat illum. Eum repellendus nemo ex impedit quasi aut libero illum in reiciendis velit sit facilis tempora 33 repudiandae repellat.
Ea ipsam enim ut quibusdam facere eos expedita dolorum ad veritatis dolor. Vel quia quas aut totam natus vel quis dolorem et natus obcaecati et nostrum in possimus dolores et sunt consequatur. Id aspernatur suscipit aut voluptatum nobis ab neque suscipit.
Et provident explicabo ex voluptas consequatur aut quam quia ad laudantium ipsum in aperiam excepturi. Quo velit placeat et voluptatem atque et corrupti illum non illo corrupti ut iusto reprehenderit et facilis optio et veritatis velit. Ea ullam consequatur ex earum omnis sit enim nihil ut mollitia consequuntur et porro consequatur.
Et odit eveniet id quas voluptatem est neque quod non fuga fuga aut sapiente ullam sed sequi voluptatem. Hic reprehenderit placeat eum esse amet ea libero libero rem corporis facere.
Et molestiae vero et autem dolorem quo officia corrupti non nisi consectetur eos laboriosam natus nam sint cumque. Aut recusandae veniam aut accusantium nisi sed soluta voluptas. Non blanditiis cumque sed odio internos est reiciendis quas.
Et sunt officiis est mollitia consequatur est incidunt praesentium qui dolorum ratione et ducimus dicta ut doloremque quasi. Qui iste atque aut beatae cumque ut porro debitis. Est exercitationem dolorem sit consequatur deleniti sit veritatis vitae non quas deserunt. Vel cumque nihil non officiis tenetur et dolores voluptatibus in saepe rerum et nihil quidem et dolores rerum.
Ea similique ipsa et Quis totam est dolorem architecto. Non repudiandae accusantium ut animi tempore et rerum quod. Aut tempora quia qui similique vero id consequatur perferendis.
Non provident unde et similique aliquam ut veniam exercitationem et earum excepturi qui sapiente rerum. Ut eligendi fugit et rerum tempora sit impedit dicta. Est veritatis nisi hic illo ratione non enim quae.
Ad eligendi quas est enim voluptas et odit sequi At delectus odit. Qui vero quia eum rerum rerum est internos fuga nam autem ratione qui aliquid nihil et odio enim. Cum dolores maxime harum atque et aliquid eius ut voluptatum necessitatibus est minus fugiat ut voluptates atque. Aut incidunt labore vel excepturi laudantium sed sapiente dignissimos et dignissimos sint ab consequatur animi ab iure placeat.
Aut quia sunt et quia facere ut mollitia quis ut ipsa rerum et esse quia. Et voluptatem neque sed iure excepturi eos nemo voluptatem At commodi architecto 33 illo beatae ut odit maxime! Ut quia eveniet aut labore alias et illum consequatur rem autem voluptas. Aut asperiores repellendus aut veritatis dolor et praesentium delectus non saepe voluptas qui facilis voluptas et dolor nemo.
Et dolorem provident ut totam blanditiis ea alias rerum 33 sint perferendis. Et repudiandae pariatur ut aliquam doloremque id quasi iste ut velit obcaecati!
Eum quisquam dignissimos ex dolor unde eos magni eaque. Ab nostrum sequi et quod deleniti aut consequuntur animi.
Ut deleniti nulla et veritatis quis et consequatur deleniti a veritatis consequatur aut nihil voluptatem. Qui libero libero qui dolor excepturi a voluptatem itaque et necessitatibus unde ea facere aspernatur eos doloremque architecto.
Aut sunt neque ut debitis totam est sequi sunt. Eos magnam accusantium est dignissimos ipsam eum quia reprehenderit non nobis quidem est repudiandae mollitia? Ut libero omnis ad molestiae consectetur eos quaerat voluptatem ut officiis facilis aut harum voluptas sed quod voluptatem est voluptatem velit.
Et quis voluptatibus ad dolore voluptas ut maxime tempore! At consequatur vitae qui quae nobis qui rerum quam et fugiat nostrum qui impedit soluta 33 iure obcaecati id rerum maxime. Ea ipsa blanditiis est aliquam totam sed voluptatibus dolore nam reprehenderit odio. Ad pariatur maxime eum deleniti laboriosam a enim galisum ea doloribus voluptate ut expedita voluptas.
Et voluptate praesentium ut vero corrupti ut dolorem odit. Vel quae iusto aut aspernatur deleniti sed aliquid labore.
Aut internos eveniet ea error nostrum sed magnam quia non deleniti quaerat aut voluptas molestiae. Sit culpa sunt non reprehenderit sint ut similique velit qui ratione assumenda qui provident culpa nam ipsam voluptatem ut repellat saepe. Et voluptas dolores ex eligendi mollitia et libero tempore!`

export default loremIpsum;