/** Text was generated with `_text-generator.ts`. */

/** A 20 paragraph corpus that should be parsable by the mock tokenizer. */
export const mockStory: string = `foo foofoo foo bar barfoobar foo foo foo barfoo foofoobar 133. bar foobarfoo barbarbar barbarbar barbarfoo bar barfoobar foofoobar 123 bar barfoobar? barfoo foofoofoo barbar foobar foobar foo 222 foo 113 barfoobar foofoo foo 2 foobarbar bar bar foo barfoobar bar~ barbar foo foofoo barfoobar foobarfoo 11111 foobar barbar foo barfoo foobar foobar foobar barfoobar foofoo foofoo bar barbar foo~ barbarfoo foo 22 bar foobar foo barfoobar barfoo barbarbar barbar barbar foofoofoo bar 22222! foobarbar barbar 1121 foobarfoo bar 33333 barfoobar 33~~~
foobarfoo barbar 1 barbarbar foofoo barbar 22 barfoofoo! 3321 barfoo barfoofoo foofoo barfoo foobarfoo foobar 11 bar foo bar 1 bar barbar bar barfoo 3333 bar foo~~~ barbar 2222 11111 barfoobar barbar foofoo foobar bar!
232 foofoobar foofoofoo barbar foo foobar foo barfoofoo foofoobar barfoo barbar foofoobar bar foobarbar foobarbar 22 2222 3111~ barfoofoo foo foo bar foobarbar barbar foobar bar foobar foofoo foo barfoo 22222 1 311 foo foofoo. foo barbar foo barfoo foobar foofoo barfoo 11111 barbar barfoobar bar foo foofoo bar bar bar bar? barbar 3 bar 3333 barfoo 33 33 foo 22231 bar???
bar barfoobar barfoobar foobarfoo 2 22 foofoobar barfoobar barfoofoo foobar barfoofoo bar bar barbarfoo barbarbar 32222 foofoo barfoofoo~ barbarfoo barfoo foofoobar 3 33 11 foo barfoo foofoobar foofoobar foobar barbar 3333 barbarfoo barfoobar barbar 22 barfoo foobarfoo? bar 321 bar foobar foobar foofoofoo foobar bar foobar barbar 33333 foo foofoo foo foofoo foo foobarfoo foofoobar bar foobarbar? 1111 barbarbar bar bar barfoo 323 barfoo foo foo foofoofoo 11111 barbarbar barbar foobar 33333 foofoo foofoofoo bar! barbar 22131 foofoobar foobar barfoofoo barbarfoo barfoo barfoobar barfoo barbarfoo foofoo foo barfoofoo barbarbar barfoobar barbar barbarbar barfoofoo foobar! foobar barbar foobarfoo bar 111 foofoobar foofoo foobar foofoobar bar barbarbar bar foo 1111 foofoofoo foofoobar barbarbar foobar barbar.
2 barbarbar 1122 foofoo foofoo foo 11 foofoo barfoo foo barfoofoo foobarfoo foobar foobar foobar barbarfoo bar foo foofoo barbarfoo! barfoo foo foo barbar foo foobarbar foo 11 foobar foobarbar barfoobar foofoobar bar foobarbar foo barbarbar foo barfoo foobarbar. foofoobar bar bar bar foobarbar 1 barfoo foobar barfoo bar foo bar? foofoofoo barbarbar foo foofoofoo foo foo barbar bar foofoobar 2222 foobar 22 foo barbarbar foofoo foobarfoo?

\tfoo foofoo foofoofoo 3 foofoofoo foofoofoo barfoo barbarbar 33 barbarbar! foo foofoo foo barfoo barbar barfoo foofoo barfoo barfoobar barfoo bar 232 bar bar foobarfoo foofoofoo. foofoo 11 foofoobar foofoobar barfoobar 222 foofoo foobarfoo foobarfoo 111 32323 2123 111 bar 33333 foo bar foo barfoobar barfoofoo! foo foo barfoo foobar 22 barbarbar foo foo bar bar bar barfoo foo bar barfoo bar barbarbar foobarfoo! foofoofoo foobar barfoobar foofoo foobar foo foofoo 11112 foofoobar barbarfoo???

foobar barbarfoo bar foobarbar foobar 22222 1232 3 bar foofoo foo barbar~ foo foofoo barbar foo 13 foo bar foobar 21131! barfoobar barfoofoo foobarbar barbarbar 333 barbar foo foofoofoo foofoo foobar barbar bar foo barbarbar foofoobar foo 1 foofoobar foobarfoo! barfoofoo foobar barbar bar barfoo 32 foobar 13231 barbar?
bar foofoo foobar barfoobar bar barbar foo foofoo bar foo 11 barbar barfoo barfoobar bar foofoobar barbar 122 2? bar bar 33333 foofoo bar barbar barfoo foofoo 3333 foofoofoo barfoobar foo 11213 1 foo... 1 barbarbar foofoobar bar foobar foofoo foo 22 bar foofoo foo foobar 21112 barfoo 3332 foo 2~ foobarfoo foofoo bar foo bar foo barfoo barbar barbar 1223 barfoo foofoofoo foo foofoo... barbar barbarfoo barfoobar foo foofoo foobar 333 131 foofoobar foo foofoo foofoofoo foofoofoo!!!
2 foofoo bar bar foobar foofoobar foobarbar 2 foofoo! 212 barbar 331 foobarfoo foofoofoo bar bar barbarfoo foobar barfoobar foobar foofoo foofoo barfoofoo foo bar foobarbar bar barbarbar bar? 111 barfoobar 11 barfoofoo barfoobar barfoo bar barbarfoo barfoo bar? foo foo barfoo bar barfoo foofoobar barfoofoo foo bar bar foobarfoo foobarbar. foo foobarfoo barfoo foo 2222 barbar foobar 3333 barbar 22 foo barbarbar bar foobar~ bar 1111 bar foobar foo barbarbar barbar foofoo bar foofoo bar 3333 barbarfoo foo barfoo 131 foobar bar foo bar?
foo 1112 barbar barbarbar foobar foo barfoobar barfoobar foo foo foobarbar bar bar barfoo foofoo~ barbarfoo bar foobarbar bar 2213 barbarfoo barbar barbar! barfoo barbar foobarbar 21313 barbarbar 11 foobar 11 foobarfoo bar foo barfoo foobar foobar barfoo barbar barbarbar barfoo. barbarbar 232 barfoo barbarbar barbar foo bar 11 barbar bar foo foobar foofoo barbar bar...
foofoobar foofoobar foo 3 barfoo foobarbar barfoo barfoo foo~ foo bar foo foo barbarbar foo 12 333 foobar barfoo foofoofoo bar foo foo barbar bar foobarfoo foo barfoo? barbar foo bar foo foofoofoo 33333 12 bar foo barbar bar foobar.

foofoo barbar barbarbar foofoo barfoo 3333 bar barbarfoo 33. barfoofoo barbarfoo foo 322 3 21322 barfoobar barfoobar barfoo foo foofoobar barfoobar 3321 barbarfoo foobar barfoo foofoofoo foofoo~ foofoo 223 11111 foofoofoo foobarfoo 33 foo foobar barfoobar foobarfoo barfoo barbarfoo bar 2222 1231 11111. barbar foofoo bar barbar foo foobar foobarfoo barbar barfoo foofoofoo foo 3 barfoofoo foo? 112 3321 barfoobar foobar bar barbarbar foofoo 23332 foobar foofoofoo barbarbar foo 2123 11111. foobar 3211 barfoobar barfoofoo foobarfoo barfoobar 2 foo foobarbar barbarfoo 311 barfoo barbar~
foo foofoo foofoo bar barbarbar barfoo bar barbarfoo~ 1 foofoo barfoo barbarfoo foofoo foofoo barbar foo foobarfoo foo bar barfoo bar 22222 foobarbar!
foofoo foofoobar 3 foo foofoo foo foobar foo bar foo barbar barfoobar bar barfoo foofoo barfoo foo foobar 2222~ foofoobar barfoofoo foofoo 32 barbarfoo foofoo 22 foobarfoo barbar 33333 bar barfoo barfoobar barfoo bar 3121 foo~
bar foo barfoobar foo barbar foo barfoobar bar 3 11 foo 1333 foofoo barfoo foobarbar foofoo foobar foo foobarfoo? barfoobar foo bar barfoofoo foofoobar barfoobar barfoobar barbarfoo 1 barbarbar barbar bar.
foobar foobarfoo foofoo 22 barfoo barfoo foo foofoobar foofoo bar bar 32112 2222 barbarfoo foofoo foofoobar barbarbar~ 311 foofoofoo foofoo foofoofoo barfoofoo foo 3 bar foobarfoo foo barbar bar foo barbarfoo foo barbarfoo??? barbarfoo 22 foofoobar foo foobar bar barbarfoo barbar foobar foofoofoo bar foofoofoo foo barbar foobar bar foobar foobar foofoofoo. foobarbar foobar bar barfoo bar barfoobar barbarfoo foobarfoo barfoofoo bar barfoo 3233 barfoobar 2322 barbar barbar~
2 barfoobar foo foo barbar foofoo foofoofoo bar barfoobar? bar 13211 foo barbar barbarbar foobarbar barbarbar foofoo barfoo 3 barfoofoo foo foo 1111 foofoofoo foofoo bar barfoobar foobarbar barfoo? 333 foo foo foobarfoo bar foofoofoo bar barfoobar foobarbar barfoofoo barfoo foofoo barfoo barbar bar foobar foobarfoo 222 barbarbar. 1 foo foofoo barfoo barfoobar 21 foobar foo~
foofoobar foofoofoo barbarfoo foofoofoo foo foofoo foofoobar 1 foofoo foo foofoofoo barbarbar~ bar 2222 bar foobarbar foobarfoo bar 2333 bar foofoofoo barfoobar foofoo foobar 33333 3333 barfoobar barfoobar bar barfoo foofoo! foobar 222 foo foofoobar bar bar foo foo 22111 foofoofoo foobar bar 33333 foofoo bar barfoobar barbar bar foofoobar barbarfoo.
3 foo 2123 foo 23221 foobarfoo 22 bar 1111 barfoo. 11111 barbarbar 111 bar 223 foofoo barbarbar 2 foobar foofoobar foofoo bar 1? barfoobar barbarbar bar foo barbarfoo 33333 bar foobar 22132 barfoo barbarbar 11 foo 22222!
foofoofoo 11111 foofoo bar barbarfoo bar foofoobar barbar foofoobar 333 33! 33 bar barfoo barbarbar foofoobar foofoo barfoofoo barbarfoo 2? bar foo barfoofoo foofoofoo 3 foofoobar foo bar bar!!!
foofoo foo foobarbar barbarfoo barfoo foo bar foo barbarbar foobar foobarbar foofoo barbarfoo foofoo! barbarfoo foobar foo barfoo foo barbar foofoo barfoo 33 foobar bar bar barbarbar barfoobar 11111.`;

/** A few paragraphs that start with a comment. */
export const startComments: string = `## foo bar foofoo 21 barbarbar barbar foofoobar barbarfoo foo bar barfoofoo foobarbar foobar barfoofoo foo 3 bar! bar barbar foo bar foofoo foofoo foo foofoo!
## barfoo bar foo foofoo foo bar bar barfoobar foo foobar barbarfoo barbar foofoo barbar 3 foo barbar foobar? foobar barfoobar foofoo foobarfoo foofoo 3 321 foobarbar barbarbar foobar.
barfoo 112 bar bar 3233 barfoofoo foobar 2122. 2111 bar foofoo foo foo bar foobarbar 2 barfoo~
foofoofoo bar bar barbar foofoo barbar barfoobar bar foofoofoo bar foo 1111 foobar foobar barfoofoo foofoo bar barfoobar~~~ foo foo barfoo bar foofoo foo foobarbar foofoofoo barbarbar foofoo foobarbar foofoo bar barbarbar bar barbar bar barbarfoo barbarfoo...
foofoo 111 barfoo foofoo barbar foo 22 foofoo bar! foo foo 3333 foo foobarfoo 1 foofoo foobar. bar foo foobarfoo bar foofoo foofoobar foo 2 33 foo?
foofoo bar foobar foobar bar foo barbar 333 bar foobarfoo foo foobar foobarfoo foo foobar foobarbar bar foofoo 311~ foobar foobarfoo 1 barbarbar barbarfoo barfoo 222 barbarbar foofoobar. barfoo bar foobar foobar 33 foofoobar 3 barfoo 33 23121~ foobar 22 13211 foo barbar 22 bar foofoo 233 foo foofoobar foo foo foobarbar foo barbarfoo foo foofoofoo barfoobar foobarbar!`;

/** A few paragraphs interrupted by a comment. */
export const middleComments: string = `barfoobar foobar barfoo foobarfoo 2222 1121 1222 barbarbar foobar foofoo barfoofoo foobar foofoo 1111~ foo barfoo barfoo foofoofoo foobarfoo bar foofoo foo bar barfoofoo barbar barbarfoo foobarbar foofoofoo... barfoo 23323 foofoo 1111 3112 bar foo bar barfoo foofoofoo bar foobarbar barbar 1332~ foofoo foo foo foobarfoo 3 bar foo 222 foofoofoo foo foobarfoo barbar barbarbar foofoofoo foofoofoo foofoo... foobar foobarbar 1112 foofoofoo bar foofoo foobarfoo bar barfoobar 3333 foobarfoo foofoo foobarfoo barfoo barfoo bar bar bar foofoofoo!
barbarfoo barfoofoo barbar 1 bar foo barfoofoo barbar foofoobar barbarfoo foofoofoo bar barbar foobarbar foofoofoo foofoofoo barfoo foofoofoo bar! foo barfoofoo barbarfoo foo bar 22222 barbar barfoobar barfoofoo foo barbarfoo barfoo foofoo bar foobarbar foobarfoo!!! foobar barbar 11331 foofoofoo 322 barbarbar foofoo foobar barfoo barfoo? foo barbar foo foofoo bar bar foobar 33333 32 foo barbarbar~ foobar barbar foobarfoo foobar foo foofoobar barfoofoo foobarfoo! foobar barfoobar barbar barbar bar foo 2222 foo barfoofoo.
## 1111 foobarbar barfoo foobar barbarbar 1111 barfoo barbar foobarbar barfoo 22 foofoofoo~ 11232 foofoo foobar 1232 barfoo foo 222 3333 foofoofoo barbarbar foo barbar.
## bar 231 foo 2 foobar foofoobar foo foobarfoo 1 barbarfoo bar barfoo foo 3333!
foofoo bar foofoobar foobar bar foobar 3 foofoofoo bar barfoofoo foofoo barbarbar 33 1 bar. foofoo foobar 111 foobar bar foofoo foobar barbar barfoobar foobarfoo 22 bar barbar 21 barbarfoo foo foofoo bar foofoobar 3333!
foo barfoo bar barbar barbarfoo foofoo 211 31222 foofoobar barfoo foobar barfoobar foofoo? foobarfoo bar foofoobar barfoo barbar barbarbar foobar foobarfoo. foofoo 121 barbar barfoofoo barfoofoo barbar barbar foobar foobarfoo 22! bar 22 foobar foofoofoo bar bar barfoo barfoo 2222 barfoo foo foobarbar 33 barbarbar? 211 barbar bar foo barfoo barbar barbar 31132 barbar 3333 foobarbar foobar 3 foobarfoo~ foobar 3223 barfoo barbarfoo barbarfoo foobarbar 111 foo bar bar foobarbar foo foobarfoo bar~~~`;

/** A few paragraphs that end with a comment. */
export const endComments: string = `33 foobar foobarbar bar foobar foofoo foobar barfoofoo bar barfoobar foo 21 barfoofoo foobarfoo foofoofoo??? foobar barbar 223 bar bar foobar foobar foofoo barbar bar 2222 barbar bar foo 11 foobarbar 2222 bar foo. 11 barbarbar bar 3323 foobar foobarfoo foofoo 333 bar foobarbar 22223 foofoo barfoofoo barbarfoo. barbarfoo foobarbar bar foobarfoo foobarbar barbar foofoo barbarbar. 2211 foo foobar foo foo bar foobarbar barfoofoo barbarbar foofoofoo foo foofoofoo barfoofoo barfoofoo barbarbar foo barfoofoo?
1111 barbar barbar foofoo bar foobarbar 31 foofoofoo barfoo bar barbarbar 1333 foofoobar foo barbar foofoobar foo! barbar barfoo bar barfoobar bar barbar bar 333 3311 foofoofoo? bar foo foobarfoo barfoo foobarfoo foobarbar foo barfoobar foobarfoo 1 barbar bar foofoo bar foofoobar foobarbar foofoofoo bar foofoofoo?
barbarfoo barfoobar foofoofoo barfoo bar bar barfoobar foo 333 barfoo foofoofoo!!! foofoo bar 22223 bar 13 bar bar foobarbar 33 foofoo barfoo~~~
bar foobar 3333 barfoo 2222 foofoofoo 2 22222 foobar foofoobar 213 barfoofoo foobar barfoobar! foofoo foofoo foobarbar 231 2 bar 3 1211 foofoofoo barfoofoo barbarbar 231 barbarbar foo 221 foobar foobar foobar foo 32211~ foo foobarfoo foofoo bar bar foobarfoo barfoobar foofoo foobarfoo barbarfoo foo barfoo 333 foo foo foofoo bar~
## foobarbar barbar barbar barfoo foofoo barbar foofoofoo foobar barfoobar barbar 11 bar 333?
## 22222 bar foobarfoo barfoofoo foo foobarfoo bar bar bar foobar 212 barfoobar foofoo foo 3 foofoo? 222 foo barbarbar foobar barfoofoo bar 2222 barbarfoo barfoo barfoobar~`;

/** A few paragraphs with comments scattered throughout. */
export const withComments: string = `## barfoo barbar barbarfoo foobar foofoo foobarfoo bar foobarbar foobar foo? foobar foofoofoo barfoofoo barfoo bar barbarfoo foofoo foofoo foo barfoobar barbar foofoofoo.
## foobar barfoobar barbarfoo foo foofoo bar 1 barfoo barbar barbarbar foo barbarbar 333 barfoofoo foo barbarfoo barbar barfoo foo 2.
foo foobar 2121 bar 32111 bar foobar barfoofoo 1 2 333 foo foo foofoo 21 22233? bar foobar foofoo 3233 2 bar 12323 foo! barfoo barfoofoo bar 323 foofoo barfoofoo foobarfoo foo barfoofoo 22 foo barfoo foo foofoo 1111 33 foofoofoo foofoofoo foo 133. foobarfoo 1222 barfoofoo bar foobar bar foofoo 2113 bar bar foobarfoo~ foofoobar foofoobar barbarbar 1 1 1111 foofoobar barfoofoo barfoo bar foofoobar 11 barfoo barfoo 3 foobarbar foobar barfoobar barfoo.
bar bar foofoo barfoofoo foo foo foobarbar foobar! bar foofoofoo barfoo barbarbar barbarfoo foo barfoofoo foobar foo foobarbar 3 bar foo foo foobar 322 foofoo bar 1 bar??? foofoofoo foo foo barbarbar 2 foo barbarfoo foobarfoo 11331 barfoo 1 barfoofoo barfoo bar bar barfoobar 1212 barbarfoo foofoofoo foobarbar... foo foobar barbar foo foofoo bar bar foo foo bar barbar bar 11221 333. foo foobarfoo foofoo bar 3 bar barfoo 32233 foofoofoo barfoobar foofoo foobarfoo.
## bar 11 barfoo bar barbar 111 bar 3222 foo foo foo foobar barfoobar barfoofoo foo foofoo bar barbarfoo. barbar barbarfoo bar barfoofoo foo foo bar barbarfoo foofoofoo barfoobar foo barbarfoo barfoo.
## foobar foo foo 32221 barfoofoo barbar foobar foo barbar foo foo bar barfoofoo foo foofoofoo foo 11 222!!!
barfoobar 1 barbar foobarfoo foofoo foobar foo foo... 21 barbarbar 111 foofoo bar foo foo bar foo 111 foo bar foo bar barfoo foofoofoo 11223! 333 bar foo foo foo barbarbar foofoo foobar barfoo foofoo foobar 33333 barbarbar barbarbar foo foofoo foo 1 foo 2132!!! barbarfoo barfoofoo 2222 11211 foo bar barfoo barbar? foofoobar bar bar barbar 321 foobarfoo foofoobar bar 331 barfoo barbar 121 barfoo foobar 13313 barfoo!
foofoo foofoo 1 2 barfoofoo barbarbar barfoo 222 foobar foofoofoo bar! foo 111 foofoo foofoobar foobar 2313 foo barfoofoo foobar foobarbar foobar. foobar barfoobar barbar foofoobar foo foobarfoo bar foo barfoofoo 11111! bar foofoobar 33 barfoobar foobarbar foofoo foo 32233 foofoofoo foobarbar barbarfoo~ foofoobar bar barbarbar foo foobarfoo barfoofoo foobarfoo foofoo foobar barfoofoo 3121 barbar 11 barbar? foo 1 bar bar foobarfoo 3213 13 foobar foo barfoo bar barbar barbarfoo foo foobar foofoofoo foobarfoo foo!!!
## barfoo barbarbar foobar foofoo barfoo foobarfoo foobar barbarfoo foofoo barbarfoo 2 barfoofoo foobar barbarbar barbar foofoofoo foofoobar foo barbar.
## bar foobarfoo 1 bar barfoofoo foobarfoo foobarbar bar foo bar barbar barfoo bar barfoo foobarfoo barfoo barfoofoo foofoofoo barbar barbarfoo! foobar foofoobar barbarbar barbar bar foobar foo foo foobar barbar foo bar bar 22212 22121 foofoo?`;